export const FETCH_SERVICES_START = 'FETCH_SERVICES_START';
export const FETCH_SERVICES_SUCCESS = 'FETCH_SERVICES_SUCCESS';
export const FETCH_SERVICES_FAILURE = 'FETCH_SERVICES_FAILURE';

export const FETCH_ENQUIRY_TYPES_START = 'FETCH_ENQUIRY_TYPES_START';
export const FETCH_ENQUIRY_TYPES_SUCCESS = 'FETCH_ENQUIRY_TYPES_SUCCESS';
